/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VUES.AUTH.Registre;

import MODELS.Account;
import static MODELS.Client.createClient;
import MODELS.Img;
import MODELS.MailBoxLayer;
import MODELS.Personne;
import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author hamza
 */
public class RegistreStep3 extends javax.swing.JPanel {

    Account am = new Account();

    /**
     * Creates new form RegistreStep3
     */
    public RegistreStep3() {
        initComponents();
        setFields();
    }

    private void setFields() {
        email.setText(Personne.getEmail());
        ville.setText(Personne.getVille());
        address.setText(Personne.getAdresse());
    }

    private String getDate() {
        if (jXDatePicker1.getDate() != null) {
            return (jXDatePicker1.getDate().getYear() + 1900) + "-" + (jXDatePicker1.getDate().getMonth() + 1) + "-"
                    + jXDatePicker1.getDate().getDate();
        }
        return "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ville = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        email = new javax.swing.JTextField();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        password = new javax.swing.JPasswordField();
        Conirmation = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        error = new javax.swing.JLabel();
        cinError = new javax.swing.JLabel();
        emailError = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        c1Path = new javax.swing.JTextField();
        c1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        c2Path = new javax.swing.JTextField();
        c2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Email :");

        jLabel2.setText("Ville :");

        jLabel3.setText("Adresse : ");

        jLabel4.setText("Date de naissance :");

        jButton1.setBackground(new java.awt.Color(4, 96, 96));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Créer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Mot de passe :");

        jLabel10.setText("Confirmer :");

        error.setForeground(new java.awt.Color(222, 0, 0));

        cinError.setForeground(new java.awt.Color(222, 0, 0));

        emailError.setForeground(new java.awt.Color(222, 0, 0));

        jLabel5.setText("CIN face 1:");

        c1.setBackground(new java.awt.Color(15, 122, 122));
        c1.setForeground(new java.awt.Color(255, 255, 255));
        c1.setText("choisir");
        c1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c1MouseClicked(evt);
            }
        });

        jLabel7.setText("CIN face 2:");

        c2.setBackground(new java.awt.Color(15, 122, 122));
        c2.setForeground(new java.awt.Color(255, 255, 255));
        c2.setText("choisir");
        c2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup().addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel5).addComponent(jLabel7))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                                javax.swing.GroupLayout.Alignment.TRAILING,
                                layout.createSequentialGroup().addGroup(layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(password, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(email, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ville, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(address, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(
                                                jXDatePicker1, javax.swing.GroupLayout.DEFAULT_SIZE, 202,
                                                Short.MAX_VALUE))
                                        .addGap(167, 167, 167))
                                .addGroup(layout.createSequentialGroup().addGroup(layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(emailError, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cinError, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(error,
                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Conirmation, javax.swing.GroupLayout.Alignment.LEADING,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup().addGroup(layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(c2Path, javax.swing.GroupLayout.Alignment.LEADING,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                                .addComponent(c1Path, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(c1).addComponent(c2))))
                                        .addGap(0, 0, Short.MAX_VALUE)))));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup().addGap(31, 31, 31).addComponent(cinError)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(emailError)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ville, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel4)
                                .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Conirmation, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5).addComponent(c1Path, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(c1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7).addComponent(c2Path, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(c2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(error)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1).addContainerGap()));
    }// </editor-fold>//GEN-END:initComponents

    private void topFrameDispose() {
        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        topFrame.dispose();
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed

        String d = getDate();
        String email_ = email.getText();
        String ville_ = ville.getText();
        String address_ = address.getText();

        if (!email_.isEmpty() && !ville_.isEmpty() && !address_.isEmpty()) {

            Personne.setVille(ville_);
            Personne.setAddress(address_);
            Personne.setDate_naissance(d);
            // verification cin disponibilité

            cinError.setText("");
            // verification si l'email est valide réelement
            if (MailBoxLayer.checkSMTP(email_)) {
                emailError.setText("");
                Personne.setEmail(email_);
                // verification que les mots de passes entrer sont egaux
                if (password.getText().equals(Conirmation.getText())) {
                    // verification si le mot de passe entrer contient que les chifres
                    if (password.getText().matches("[0-9]+")) {
                        Personne.setPassword(password.getText());
                        try {
                            long numAccount = Account.createAccount();
                            createClient(numAccount);
                            Img.store(c1Path.getText(), Personne.getCin());
                            Img.store(c2Path.getText(), Personne.getCin());
                            JOptionPane.showMessageDialog(this, "Votre compte a été crée avec success", "Success", JOptionPane.INFORMATION_MESSAGE);
                            //envoyer email
                        } catch (SQLException | ParseException ex) {
                            JOptionPane.showMessageDialog(this, "Erreur lors de création de compte\n" + ex.getMessage(), "fatal erreur", JOptionPane.ERROR_MESSAGE);
                        } catch (IOException ex) {
                            Logger.getLogger(RegistreStep3.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        // new SendEmail(cin_, "Creation d'un compte", "votre demande de Creer un compte
                        // e été envoyer avec succès\n nous allons vous contacter le plutot possible");
                    } else {
                        error.setText("Mot de pass doit contient que des chifres !!!");
                    }
                } else {
                    error.setText("les mots de passes ne sont pas egaux !!");
                }
            } else { // si l'email n'est pas valide
                emailError.setText("email n'existe pas,entrer un email valide");
            }

        } else {
            JOptionPane.showMessageDialog(this, "verifier que vous avez remplir tous les champs correctement!",
                    "Warning", JOptionPane.WARNING_MESSAGE);
        }

    }// GEN-LAST:event_jButton1ActionPerformed

    public String getPath() {
        JFileChooser chooser = new JFileChooser();
        // chooser.setCurrentDirectory(new java.io.File("."));
        // Setting Up The Filter
        FileFilter imageFilter = new FileNameExtensionFilter("Image files", ImageIO.getReaderFileSuffixes());
        // Attaching Filter to JFileChooser object
        chooser.setFileFilter(imageFilter);
        chooser.setDialogTitle("Choisir CIN");
        chooser.setAcceptAllFileFilterUsed(false);
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            // System.out.println("getCurrentDirectory(): "+ chooser.getCurrentDirectory());
            // System.out.println("getSelectedFile() : " + chooser.getSelectedFile());
            return chooser.getSelectedFile().getAbsolutePath();
        } else {
            return null;
        }
    }

    private void c1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_c1MouseClicked
        // TODO add your handling code here:
        String path = getPath();
        try {
            c1Path.setText(path);
        } catch (Exception ex) {
            c1Path.setText("");
        }
    }// GEN-LAST:event_c1MouseClicked

    private void c2MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_c2MouseClicked
        // TODO add your handling code here:
        String path = getPath();
        try {
            c2Path.setText(path);
        } catch (Exception ex) {
            c2Path.setText("");
        }
    }// GEN-LAST:event_c2MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Conirmation;
    private javax.swing.JTextField address;
    private javax.swing.JButton c1;
    private javax.swing.JTextField c1Path;
    private javax.swing.JButton c2;
    private javax.swing.JTextField c2Path;
    private javax.swing.JLabel cinError;
    private javax.swing.JTextField email;
    private javax.swing.JLabel emailError;
    private javax.swing.JLabel error;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField ville;
    // End of variables declaration//GEN-END:variables
}
